version: "3"

services:
  app:
    image: nvidia11
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ElasticFusion:/home/user/ElasticFusion
    network_mode: host
    entrypoint: /compose-entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
